import axios from 'axios';
import dotenv from 'dotenv';
dotenv.config();

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'; // Optional for dev; avoid in prod

// Basic cleaner to strip HTML tags and junk characters
function cleanText(raw) {
  if (!raw || raw.trim() === '') return '';

  // Remove HTML tags
  let text = raw.replace(/<[^>]*>/g, ' ');

  // Remove unicode control characters and non-printable chars
  text = text.replace(/[\u0000-\u001F\u007F-\u009F]/g, ' ');

  // Replace multiple spaces/newlines with single space
  text = text.replace(/\s+/g, ' ').trim();

  return text;
}

export async function getAISummary(rawTextContent) {
  const textContent = cleanText(rawTextContent);

  if (!textContent) {
    return '⚠️ No valid content provided for summarization.';
  }

  const prompt = `
You are an expert AI summarizer specialized in reading coding challenge pages (including hackathons, hiring challenges, and ideation contests) and generating short, structured summaries in English.

Your job is to help developers and professionals quickly understand the challenge by extracting the most relevant details from the provided description **only**.

Here is the extracted text content of the challenge page:
${textContent}

⚠️ Very important instructions:
- Your output **must only** include the 3-line summary in the format below.
- ❌ Do NOT add titles, markdown headers (like ###), bullet points, or any other extra commentary.
- ❌ Do NOT hallucinate any information that is not explicitly found in the input content.
- ✅ Use "Not specified" if any detail is missing.
- ⚠️ If the page content is unreadable or lacks enough info, respond with:
  "⚠️ Challenge summary not available due to unreadable or insufficient content."

Here is the exact required format (example):

Challenge: Juspay Hiring Challenge 2025  
💡 Type: Hiring Challenge | 💼 Organiser: Juspay | 📍 Location: Danaher India Development Center (IDC), Bangalore | 🎯 Eligibility: Python Programming | 📈 Experience: 4+ years | 🏆 Rewards: 42 LPA | 🕒 Deadline: June 25, 2025  
🔗 Apply: https://www.hackerearth.com/challenges/hiring/juspay-software-engineer-hiring-challenge-2025/

Please return only the summary in this exact format.
`;


  try {
    const response = await axios.post(
      'https://openrouter.ai/api/v1/chat/completions',
      {
        model: 'meta-llama/llama-4-scout:free',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.3,
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
          'Content-Type': 'application/json',
        },
        timeout: 15000,
      }
    );

    const summary = response.data.choices[0].message.content.trim();
    return summary || '⚠️ No summary generated by AI.';
  } catch (error) {
    console.error('AI summarization failed:', {
      status: error.response?.status,
      data: error.response?.data,
      message: error.message,
    });
    return '⚠️ AI summarization failed. Please check the logs.';
  }
}
